config/routes.rb
TestingDeviseApp::Application.routes.draw do
  resources :devices do
    member do
      put 'mark_as_available'
      put 'mark_as_unavailable'
      put 'mark_as_failing'
    end
  end

  resources :projects
  authenticated :user do
    root :to => 'welcom#home'
  end
  root :to => 'welcom#home'

  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout' }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
        can :manage, :all
    else #if user.tester? or user.developer?
        can :read, Device
        can :write, Device
        can :mark_as_unavailable, Device
        can :mark_as_available, Device, :user_id => user.id
        can :read, Project
        can :read, User
        cannot :write, User
    end
  end

  def as_json
    abilities = []
    rules.each do |rule|
      abilities << { can: rule.base_behavior, actions: rule.actions.as_json, subjects: rule.subjects.map(&:to_s), conditions: rule.conditions.as_json }
    end
    abilities.to_json 
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  SOS = %w(Android iOS BlackBerry)
  TYPES = %w(SmartPhone Tablet)
  STATUSES = %w(available unavailable failing)
  
  attr_accessible :color, :description, :id_inventario, :no_serie, :so, :type_device, :udid, :version, :status, :start_using, :user_id, :project_id, :take_cable

  #Associations
  belongs_to :user
  belongs_to :project 

  #Validations
  validates :description, :type_device, :version, presence: true
  validates :type_device, presence: true, inclusion: {in: TYPES, message: '%{value} is not a valid Type of device'}
  validates :so, presence: true, inclusion: {in: SOS, message: '%{value} is not a valid SO'}
  validates :status, presence: true, inclusion: {in: STATUSES, message: '%{value} is not a valid STAUS'}
  validates :id_inventario, presence: true, uniqueness: true
  validates :no_serie, presence: true, uniqueness: true
  validates :udid, presence: true, uniqueness: true
  validates :user, presence: true, if: :unavailable?
  validates :project, presence: true, if: :unavailable?
  validates :start_using, presence: true, if: :unavailable?

  #delegates
  delegate :name, :to => :user, :prefix => true, :allow_nil => true
  delegate :name, :to => :project, :prefix => true, :allow_nil => true

  #Instance methods

  state_machine :status, :initial => :available do

    before_transition :unavailable => any, :do => :clean_using_information
    before_transition :available => :failing, :do => :clean_using_information

    event :mark_as_unavailable do
      transition :available => :unavailable
    end

    event :mark_as_failing do
      transition :available => :failing
    end

    event :mark_as_available do
      transition [:unavailable, :failing] => :available
    end

    state :unavailable do
      validates_presence_of :user
    end
  end

  SOS.each do |so_name|
    define_method "#{so_name.downcase}?" do
      so == so_name
    end
  end

  TYPES.each do |type_name|
    define_method "#{type_name.downcase}?" do
      type == type_name
    end
  end

  #private methods
  private
  def clean_using_information
    self.user = nil
    self.project = nil
    self.start_using = nil
    self.take_cable  = nil
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :customer, :key, :name
  
  validates :name, presence: true
  validates :customer, presence: true 
end

app/models/user.rb
#This reuire is to support the encryp/decrypt passwords like in INNOVA
require Rails.root.join('lib', 'devise', 'encryptors', 'md5')


class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable 
  attr_accessible :name, :email, :password, :remember_me, :admin, :tester, :developer

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false


  #The follow functions are to support the encryp/decrypt passwords like in INNOVA
  def password_salt
    'Th1s Jus7 50m3 3ncRypti0n k@ys'
  end

  def password_salt=(new_salt)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
    render :json => { :errors => exception.message }, :status => 422
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  load_and_authorize_resource
  respond_to :json

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    device = Device.find(params[:id])
    device.destroy
    respond_with(device)
  end

  # PUT /devices/1/mark_as_available
  def mark_as_available
    @device = Device.find(params[:id]) 
    respond_with(@device) unless @device.mark_as_available
  end


  # PUT /devices/1/mark_as_unavailable
  def mark_as_unavailable
    @device = Device.find(params[:id])
    @device.user = current_user
    @device.start_using = Time.now
    @device.project_id = params[:project_id]
    @device.take_cable = params[:take_cable]
    respond_with(@device) unless @device.mark_as_unavailable
  end


  # PUT /devices/1/mark_as_failing
  def mark_as_failing
    device = Device.find(params[:id])
    device.mark_as_failing
    respond_with(device)
  end

=begin
  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
=end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  respond_to :json

  # GET /devices
  # GET /devices.json
  def index
    @projects = Project.all
  end

end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type_device
    = f.text_field :type_device
  .field
    = f.label :so
    = f.text_field :so
  .field
    = f.label :version
    = f.text_field :version
  .field
    = f.label :no_serie
    = f.text_field :no_serie
  .field
    = f.label :id_inventario
    = f.text_field :id_inventario
  .field
    = f.label :udid
    = f.text_field :udid
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :color
    = f.text_field :color
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %tr
    %th Type device
    %th So
    %th Version
    %th No serie
    %th Id inventario
    %th Udid
    %th Description
    %th Color
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td= device.type_device
      %td= device.so
      %td= device.version
      %td= device.no_serie
      %td= device.id_inventario
      %td= device.udid
      %td= device.description
      %td= device.color
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Type device:
  = @device.type_device
%p
  %b So:
  = @device.so
%p
  %b Version:
  = @device.version
%p
  %b No serie:
  = @device.no_serie
%p
  %b Id inventario:
  = @device.id_inventario
%p
  %b Udid:
  = @device.udid
%p
  %b Description:
  = @device.description
%p
  %b Color:
  = @device.color

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/layouts/_alert.html.haml
.alert.alert-alert
  %a.close{"data-dismiss" => "alert", :href => "#"} x
  %p= alert

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %p
      = "Powered By"
      = link_to "Itexico.com", "http://itexico.com"

app/views/layouts/_header.html.haml
%header
  .navbar-inner
    .container
      %a{:class => "btn btn-navbar", "data-target" => ".nav-collapse", "data-toggle" => "collapse" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a#logo.brand{:href =>"#"}
      = link_to t('application.name'), '#', id: "title"
      %nav
        %ul.nav
          %li.divider-vertical
          %li= link_to t('menu.primary.home'), "#"
          %li.divider-vertical
          %li= link_to t('menu.primary.help'), "#"
          %li.divider-vertical
          %li.dropdown
            %a{:href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown" }
              = t('menu.primary.sig_in')
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Action1", "#"
              %li= link_to "Action2", "#"
              %li.divider
              %li= link_to "Action3", "#"
          %li.divider-vertical
      .btn-group.pull-right
        %a.user.btn.dropdown-toggle{:"data-toggle" => "dropdown"}
          %i.icon-user
          -if user_signed_in?
            = current_user.email
          -else
            = "guesst"
          %span.caret
        %ul.dropdown-menu
          %li
            -if user_signed_in?
              = link_to t("devise.login.sign_out"), destroy_user_session_path, :method => :delete
            -else
              = link_to t("devise.login.sign_in"), new_user_session_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title=TestingDeviseApp
    = stylesheet_link_tag "application", media: "all"
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = javascript_include_tag "application"
    = csrf_meta_tags
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  %body{"data-spy" => "scroll", "data-target" => ".bs-docs-sidebar", "data-twttr-rendered" => "true"}
    = yield
    = render 'layouts/footer'

app/views/layouts/login.html.haml
!!!
%html
  %head
    %title iTexico App
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  %body.login
    .container
      .row
        #alerts-container.span12
          - if alert
            = render 'layouts/alert', :alert => alert
      .row
        .span4.offset4
          .login-container
            .inner.well
              = yield

app/views/welcom/home.html.haml
#alerts-container.container
  - if notice
    = render 'layouts/alert', :alert => notice

#header-region
#main-region.container
#dialog-region
= javascript_tag do
  $(function() {
  var current_user_object = {id: "#{ current_user.id}",email: "#{ current_user.email}",admin: "#{ current_user.admin?}",tester: "#{ current_user.tester?}",developer: "#{ current_user.developer?}"};
  var ability = '#{current_ability.as_json.html_safe }';
  ManagerDevicesApp.Authorization.start({current_user_object: current_user_object, ability: ability});
  ManagerDevicesApp.start();
  });

:javascript
  I18n.defaultLocale = "#{I18n.default_locale}";
  I18n.locale = "#{I18n.locale}";